force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Version__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Cloned Versions</relationshipLabel>
    <relationshipName>Cloned_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectVersionTriggerHandler.cls
public class ProjectVersionTriggerHandler {

    /* this method is called from before insert Project Version trigger */
    public static void handleBeforeInsert(List<Project_Version__c> newVersions){
        Set<Id> clonedFromIdSet = new Set<Id>();
        List<Project_Version__c> projectVerionClones = new List<Project_Version__c>();
        for(Project_Version__c pv: newVersions){
            if(pv.isClone()){
                //inside isClone()
                pv.Cloned_From__c = pv.getCloneSourceId();
            }
            if(pv.Cloned_From__c != NULL){
                clonedFromIdSet.add(pv.Cloned_From__c);
                projectVerionClones.add(pv);
            }
        }
        if(!clonedFromIdSet.isEmpty()){
            handleCloningBeforeInsert(clonedFromIdSet, projectVerionClones);
        }
    }
    
    /* this method is called from handleBeforeInsert method, 
	in this method fields of Project Version are copied to the new Version */
    public static void handleCloningBeforeInsert(Set<Id> clonedFromIdSet, List<Project_Version__c> projectVerionClones){
        
    }
    
    
    /* this method is called from after insert Project Version trigger */
    public static void handleAfterInsert(List<Project_Version__c> newVersions){
        Set<Id> clonedFromIdSet = new Set<Id>();
        List<Project_Version__c> projectVerionClones = new List<Project_Version__c>();
        for(Project_Version__c pv: newVersions){
            if(pv.Cloned_From__c != NULL){
                clonedFromIdSet.add(pv.Cloned_From__c);
                projectVerionClones.add(pv);
            }
        }
        if(!clonedFromIdSet.isEmpty()){
            handleCloningAfterInsert(clonedFromIdSet, projectVerionClones);
        }
    }
    
    /* this method is called from handleAfterInsert method,
	in this method related object records are created on the new version*/
    public static void handleCloningAfterInsert(Set<Id> clonedFromIdSet, List<Project_Version__c> projectVerionClones){
        
    }
}