force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active_Version__c.field-meta.xml
<CustomField>
    <fullName>Active_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project_Version__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Version__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Versions</relationshipLabel>
    <relationshipName>Project_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/Resource_Engagement__c.object-meta.xml
<CustomObject>
    <label>Resource Engagement</label>
    <nameField>
        <displayFormat>RE# {YY}{MM}{DD}-{00000}</displayFormat>
        <label>Resource Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Engagement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddResources.cls
public with sharing class AddResources {
    @AuraEnabled
    public static ResourceWrapper fetchResources(String recordId){
        try {
            String objectName = ((Id)recordId).getSObjectType().getDescribe().getName();
            String versionId = objectName=='Project__c'? [select Active_Version__c from Project__c where Id=:recordId].Active_Version__c : recordId;

            ResourceWrapper rw = new ResourceWrapper();
            List<FieldWrapper> columns = new List<FieldWrapper>();

            List<Schema.FieldSetMember> lstFSMember = 
            Schema.Resource_Engagement__c.getSObjectType().getDescribe().fieldSets.getMap().get('AddResources').getFields();

            //prepare SOQL query based on fieldAPIs	
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : lstFSMember) {
                
                query += f.getFieldPath() + ', ';
                FieldWrapper fw = new FieldWrapper();
                fw.label = f.getLabel();
                fw.fieldName = f.getFieldPath();
                fw.editable = f.getFieldPath().contains('__r')?false:true;
                fw.dataType = String.valueOf(f.getType()).toLowerCase();
                columns.add(fw);
            }
            query += 'Id FROM Resource_Engagement__c where Project_Version__c =:versionId' ;
            List<SObject> lstRecords = Database.query(query);
            rw.records = lstRecords;
            rw.columns = columns;
            rw.versionId = versionId;

            return rw;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ResourceWrapper{
        @AuraEnabled
        public List<FieldWrapper> columns;
        @AuraEnabled 
        public List<Resource_Engagement__c> records;
        @AuraEnabled 
        public String versionId;

    }

    public class FieldWrapper{
        @AuraEnabled
        public String label;
        @AuraEnabled 
        public String fieldName;
        @AuraEnabled 
        public Boolean editable;
        @AuraEnabled 
        public String dataType;
    }
}