force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active_Version__c.field-meta.xml
<CustomField>
    <fullName>Active_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project_Version__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Version__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Versions</relationshipLabel>
    <relationshipName>Project_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/Resource_Engagement__c.object-meta.xml
<CustomObject>
    <label>Resource Engagement</label>
    <nameField>
        <displayFormat>RE# {YY}{MM}{DD}-{00000}</displayFormat>
        <label>Resource Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Engagement__c/fields/End_Date_of_Engagement__c.field-meta.xml
<CustomField>
    <fullName>End_Date_of_Engagement__c</fullName>
    <label>End Date of Engagement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Engaged_Days__c.field-meta.xml
<CustomField>
    <fullName>Engaged_Days__c</fullName>
    <label>Engaged Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Number_of_Weekdays__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Weekdays__c</fullName>
    <formula>IF(
 OR( ISBLANK(End_Date_of_Engagement__c), ISBLANK(Start_Date_of_Engagement__c) ),
0,

(5 * ( FLOOR( ( End_Date_of_Engagement__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( End_Date_of_Engagement__c - DATE( 1900, 1, 8), 7 ) ) )
-
(5 * ( FLOOR( ( Start_Date_of_Engagement__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( Start_Date_of_Engagement__c - DATE( 1900, 1, 8), 7 ) ) )

)</formula>
    <label>Number of Weekdays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Start_Date_of_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_of_Engagement__c</fullName>
    <label>Start Date of Engagement</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/GanttData.cls
/**
 * Created 23.01.2020.
 */

public with sharing class GanttData {

    @RemoteAction
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getTasksOld() {
        
        // fetching the Records via SOQL
        // List<GanttTask__c> Tasks = new List<GanttTask__c>();
        // Tasks = [SELECT Id, Name, Start_Date__c, Duration__c, Parent__c FROM GanttTask__c];

        // List<GanttLink__c> Links = new List<GanttLink__c>();
        // Links = [SELECT Id, Type__c, Source__c, Target__c FROM GanttLink__c];

        Map<String, Object> result = new Map<String, Object>{'tasks' => new List<String>(), 'links' => new List<String>() };
        return result;
    }

    @RemoteAction
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getTasks() {
        
        // fetching the Records via SOQL
        List<Resource_Engagement__c> Tasks = new List<Resource_Engagement__c>();
        Tasks = [SELECT Id, Name, Start_Date_of_Engagement__c, End_Date_of_Engagement__c, Engaged_Days__c,Number_of_Weekdays__c,Resource__r.Name FROM Resource_Engagement__c];

        // List<GanttLink__c> Links = new List<GanttLink__c>();
        // Links = [SELECT Id, Type__c, Source__c, Target__c FROM GanttLink__c];

        Map<String, Object> result = new Map<String, Object>{'tasks' => Tasks, 'links' => new List<String>() };
        return result;
    }

    @RemoteAction
    @AuraEnabled()
    public static Map<String, Object> getAllResourcesByProject() {
        List<GanttDataWrapper> ganttDataWrapperList = new List<GanttDataWrapper>();
        Set<Id> activeProjectVersionIdSet = new Set<Id>();
        for(Project__c p: [SELECT Id, Project_Name__c, Name, Active_Version__c FROM Project__c WHERE Active_Version__c != NULL ORDER BY Project_Name__c]){
            activeProjectVersionIdSet.add(p.Active_Version__c);
            ganttDataWrapperList.add(new GanttDataWrapper(p.Active_Version__c,p.Project_Name__c,null,null,'',null));
        }
        for(Resource_Engagement__c re: [SELECT Id, Name, Start_Date_of_Engagement__c, End_Date_of_Engagement__c, Engaged_Days__c, Number_of_Weekdays__c, Resource__r.Name, Project_Version__c, Progress__c 
                                        FROM Resource_Engagement__c 
                                        WHERE Project_Version__c IN :activeProjectVersionIdSet ]){
            ganttDataWrapperList.add(new GanttDataWrapper(re.Id,re.Resource__r.Name,re.Start_Date_of_Engagement__c,re.End_Date_of_Engagement__c, re.Project_Version__c, Integer.valueOf(re.Progress__c)));
        }
        Map<String, Object> result = new Map<String, Object>{'tasks' => ganttDataWrapperList, 'links' => new List<String>() };
        return result;
    }



    @RemoteAction
    @AuraEnabled()
    public static Map<String, Object> getResourcesByProject(String currentRecordId) {
        String pvId = '';
        List<Resource_Engagement__c> resourceEngagements = new List<Resource_Engagement__c>();
        List<GanttDataWrapper> ganttDataWrapperList = new List<GanttDataWrapper>();
        if(String.isNotBlank(currentRecordId)){
            Id recId = Id.valueOf(currentRecordId);
            String objName = recId.getSObjectType().getDescribe().getName();
            
            if(objName.equalsIgnoreCase('Project_Version__c')){
                pvId = recId;
                for(Project_Version__c pv: [SELECT Id, Name FROM Project_Version__c WHERE Id =: pvId]){
                    ganttDataWrapperList.add(new GanttDataWrapper(pv.Id,pv.Name,null,null,'',null));
                }
            }
            else if(objName.equalsIgnoreCase('Project__c')){
                for(Project__c p: [SELECT Id, Project_Name__c, Name, Active_Version__c FROM Project__c WHERE Id =: recId AND Active_Version__c != NULL]){
                    pvId = p.Active_Version__c;
                    ganttDataWrapperList.add(new GanttDataWrapper(pvId,p.Project_Name__c,null,null,'',null));
                }
            }
            else{
                // Show all projects and its resources
            }
            if(String.isNotBlank(pvId)){
                resourceEngagements = [SELECT Id, Name, Start_Date_of_Engagement__c, End_Date_of_Engagement__c, Engaged_Days__c, Number_of_Weekdays__c, Resource__r.Name, Project_Version__c, Progress__c FROM Resource_Engagement__c WHERE Project_Version__c =:pvId ];
                for(Resource_Engagement__c re: resourceEngagements){
                    ganttDataWrapperList.add(new GanttDataWrapper(re.Id,re.Resource__r.Name,re.Start_Date_of_Engagement__c,re.End_Date_of_Engagement__c, re.Project_Version__c, Integer.valueOf(re.Progress__c)));
                }
            }
        }
        
        Map<String, Object> result = new Map<String, Object>{'tasks' => ganttDataWrapperList, 'links' => new List<String>() };
        return result;
   }

    @AuraEnabled
    public static string createResource(String resourcedata) {
        //Map<String,String> a = (Map<String,String>)resourcedata;
        Map<String,Object> resourceMap = (Map<String,Object>)JSON.deserializeUntyped(resourcedata);
        Resource_Engagement__c resourceEngagement = new Resource_Engagement__c();
        System.debug(resourceMap.get('Start_Date_of_Engagement__c'));
        String startDateEngagement = (String)resourceMap.get('Start_Date_of_Engagement__c');
        resourceEngagement.Start_Date_of_Engagement__c = Date.newInstance(Integer.ValueOf(startDateEngagement.substring(0,4)),Integer.ValueOf(startDateEngagement.substring(5,7)),Integer.ValueOf(startDateEngagement.substring(8,10)));
        //resourceEngagement.End_Date_of_Engagement__c = resourceEngagement.Start_Date_of_Engagement__c.addDays()
        return 'sdsdsd';
   }

   
   public class GanttDataWrapper{
       @AuraEnabled
       public String identifier;

       @AuraEnabled
       public String displayLabel;

       @AuraEnabled
       public Date startDate;

       @AuraEnabled
       public Date endDate;

       @AuraEnabled
       public String parentIdentifier;

       @AuraEnabled
       public Integer progress;

       public GanttDataWrapper(String i, String l, Date sD, Date eD, String pId, Integer prgs){
           this.identifier = i;
           this.displayLabel = l;
           this.startDate = sD;
           this.endDate = eD;
           this.parentIdentifier = pId;
           this.progress = prgs;
       }
   }

}