force-app/main/default/objects/Engaged_Team__c/Engaged_Team__c.object-meta.xml
<CustomObject>
    <label>Engaged Team</label>
    <nameField>
        <displayFormat>ET# {YY}{MM}{DD}-{00000}</displayFormat>
        <label>Engaged Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engaged Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engaged_Team__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Engaged Teams</relationshipLabel>
    <relationshipName>Engaged_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engaged_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team_Engagements</relationshipLabel>
    <relationshipName>Team_Engagements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EngagedTeamTriggerHandler.cls
public with sharing class EngagedTeamTriggerHandler {
    /* this method is called from before insert Engaged Team trigger */
    public static void handleBeforeInsert(List<Engaged_Team__c> newRecords){
        Set<Id> projectVersionIdSet = new Set<Id>();
        Set<Id> teamIdSet = new Set<Id>();
        
        for(Engaged_Team__c et: newRecords){
            projectVersionIdSet.add(et.Project_Version__c);
            teamIdSet.add(et.Team__c);
        }
        Map<Id,Project_Version__c> projectVersionMap = new Map<Id,Project_Version__c>([SELECT Id, Name FROM Project_Version__c WHERE Id IN: projectVersionIdSet]);
        Map<Id,Team__c> teamMap = new Map<Id,Team__c>([SELECT Id, Name FROM Team__c WHERE Id IN: teamIdSet]);
    	for(Engaged_Team__c et: newRecords){
            //update name field
            if(projectVersionMap.containsKey(et.Project_Version__c) && teamMap.containsKey(et.Team__c)){
                et.Name = projectVersionMap.get(et.Project_Version__c).Name+' - '+teamMap.get(et.Team__c).Name;
            }
            else{
                et.Name = et.Project_Version__c + ' - ' + et.Team__c;
            }
        }
    }
    
    /* this method is called from after insert Engaged Team trigger */
    public static void handleAfterInsert(Map<Id,Engaged_Team__c> newRecordsMap){
    
    }
}