force-app/main/default/objects/Engaged_Team__c/Engaged_Team__c.object-meta.xml
<CustomObject>
    <label>Engaged Team</label>
    <nameField>
        <displayFormat>ET# {YY}{MM}{DD}-{00000}</displayFormat>
        <label>Engaged Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engaged Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engaged_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Engaged Teams</relationshipLabel>
    <relationshipName>Engaged_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engaged_Team__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Engaged Teams</relationshipLabel>
    <relationshipName>Engaged_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engaged_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team_Engagements</relationshipLabel>
    <relationshipName>Team_Engagements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Proposed_start__c.field-meta.xml
<CustomField>
    <fullName>Proposed_start__c</fullName>
    <label>Proposed start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Version__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Versions</relationshipLabel>
    <relationshipName>Project_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Proposed_Start__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Start__c</fullName>
    <label>Proposed Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/Resource_Engagement__c.object-meta.xml
<CustomObject>
    <label>Resource Engagement</label>
    <nameField>
        <displayFormat>RE# {YY}{MM}{DD}-{00000}</displayFormat>
        <label>Resource Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Engagement__c/fields/Engaged_Team__c.field-meta.xml
<CustomField>
    <fullName>Engaged_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engaged Team</label>
    <referenceTo>Engaged_Team__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Engagement__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Resource Engagements</relationshipLabel>
    <relationshipName>Resource_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_AddResources.cls
@isTest
public with sharing class Test_AddResources {
    @isTest 
    public static void TestAddResources() {
        Project__c prj = new Project__c(Project_Name__c='Test Project',Proposed_start__c=system.today());
        insert prj;
        Project_Version__c pv = new Project_Version__c(Name='Version 1',Project__c=prj.Id,Proposed_Start__c=system.today());
        insert pv;
        List<Contact> conList = new List<Contact>();
        Contact con1 = new Contact(FirstName='Test',LastName='Contact1');
        conList.add(con1);
        Contact con2 = new Contact(FirstName='Test',LastName='Contact2');
        conList.add(con2);
        insert conList;
        List<Team__c> teams = new List<Team__c>();
        Team__c team1 = new Team__c(Name='Test Team1');
        teams.add(team1);
        Team__c team2 = new Team__c(Name='Test Team2');
        teams.add(team2);
        insert teams;
        Engaged_Team__c et = new Engaged_Team__c(Team__c=team2.Id,Project_Version__c=pv.Id);
        insert et;
        List<Resource_Engagement__c> reList = new List<Resource_Engagement__c>();
        Resource_Engagement__c re1 = new Resource_Engagement__c(Project_Version__c=pv.Id, Resource__c=con1.Id,Team__c=team1.Id);
        reList.add(re1);
        Resource_Engagement__c re2 = new Resource_Engagement__c(Project_Version__c=pv.Id, Resource__c=con2.Id,Team__c=team2.Id,Engaged_Team__c=et.Id);
        reList.add(re2);
        insert reList;
        AddResources.fetchResources(pv.Id);
    }
}