force-app/main/default/objects/Assigned_Gate__c/Assigned_Gate__c.object-meta.xml
<CustomObject>
    <label>Assigned Gate</label>
    <nameField>
        <label>Assigned Gate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Gates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Gate__c/fields/Gate__c.field-meta.xml
<CustomField>
    <fullName>Gate__c</fullName>
    <label>Gate</label>
    <referenceTo>Gate__c</referenceTo>
    <relationshipLabel>Assigned Gates</relationshipLabel>
    <relationshipName>Assigned_Gates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigned_Gate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assigned Gates</relationshipLabel>
    <relationshipName>Assigned_Gates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gate__c/Gate__c.object-meta.xml
<CustomObject>
    <label>Gate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectTriggerHandler.cls
public with sharing class ProjectTriggerHandler {
    
    /* this method is called from before insert Project trigger */
    public static void handleBeforeInsert(List<Project__c> newProjects){
    
    }
    
    /* this method is called from after insert Project trigger */
    public static void handleAfterInsert(Map<Id,Project__c> newProjectsMap){
        
        List<Assigned_Gate__c> assignGateList = new List<Assigned_Gate__c>();
        List<Gate__c> gateList = [SELECT Id, Name, Sort_Order__c FROM Gate__c ORDER BY Sort_Order__c ASC];
        for(Id projectId: newProjectsMap.keyset()){
            for(Gate__c gate: gateList){
               assignGateList.add(new Assigned_Gate__c(Name=gate.Name, Gate__c=gate.Id, Project__c=projectId));
            }
        }
        
        if(!assignGateList.isEmpty()){
            insert assignGateList;
        }
        
    }
    
}