force-app/main/default/objects/Assigned_Gate__c/Assigned_Gate__c.object-meta.xml
<CustomObject>
    <label>Assigned Gate</label>
    <nameField>
        <label>Assigned Gate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Gates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Gate__c/fields/Gate__c.field-meta.xml
<CustomField>
    <fullName>Gate__c</fullName>
    <label>Gate</label>
    <referenceTo>Gate__c</referenceTo>
    <relationshipLabel>Assigned Gates</relationshipLabel>
    <relationshipName>Assigned_Gates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigned_Gate__c/fields/Gate_Id_And_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Gate_Id_And_Project_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Gate Id And Project Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Assigned_Gate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assigned Gates</relationshipLabel>
    <relationshipName>Assigned_Gates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gate__c/Gate__c.object-meta.xml
<CustomObject>
    <label>Gate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignedGateTriggerHandler.cls
public with sharing class AssignedGateTriggerHandler {
    /* this method is called from before insert Assigned Gate trigger */
    public static void handleBeforeInsert(List<Assigned_Gate__c> newRecords){
        handleUniqueAssignedGateToProject(newRecords);
    }
    
    /* this method is called from after insert Assigned Gate trigger */
    public static void handleAfterInsert(Map<Id,Assigned_Gate__c> newRecordsMap){
        
    }

    public static void handleUniqueAssignedGateToProject(List<Assigned_Gate__c> assignedGates){
        try{
            for(Assigned_Gate__c ag:assignedGates){
                ag.Gate_Id_And_Project_Id__c = ag.Gate__c +'-'+ag.Project__c;
            }
        }
        catch(Exception e){
            System.debug('Exception occurred while handling unique Gate to a Project : '+e.getMessage());
            throw e;
        }
    }
}