force-app/main/default/objects/Assigned_Gate__c/Assigned_Gate__c.object-meta.xml
<CustomObject>
    <label>Assigned Gate</label>
    <nameField>
        <label>Assigned Gate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Gates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Gate__c/fields/Gate__c.field-meta.xml
<CustomField>
    <fullName>Gate__c</fullName>
    <label>Gate</label>
    <referenceTo>Gate__c</referenceTo>
    <relationshipLabel>Assigned Gates</relationshipLabel>
    <relationshipName>Assigned_Gates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigned_Gate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assigned Gates</relationshipLabel>
    <relationshipName>Assigned_Gates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Gate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gate__c/Gate__c.object-meta.xml
<CustomObject>
    <label>Gate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Rework</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replan</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GateAssignmentHandler.cls
public with sharing class GateAssignmentHandler {
    public GateAssignmentHandler() {

    }
    
    @AuraEnabled(cacheable=true)
    public static List<Assigned_Gate__c> getAssignedGatesByProject(Id projectId){
        return [SELECT Id,Name,Project__c,Status__c,Gate__r.Name,Gate__r.Sort_Order__c 
                FROM Assigned_Gate__c WHERE Project__c =: projectId
                ORDER BY Gate__r.Sort_Order__c asc];
    }

    @AuraEnabled
    public static List<Assigned_Gate__c> updateAssignedGatesByProject(Id projectId,Id gateIdToComplete){
        List<Assigned_Gate__c> assignedGates = getAssignedGatesByProject(projectId);
        Integer noOfGatesAfter = 0;
        for(Assigned_Gate__c ag: assignedGates){
            String currentStatus = ag.Status__c;
            // if(currentStatus == 'In Progress')
            if(noOfGatesAfter < 1){
                ag.Status__c = 'Completed';
                if(ag.Id == gateIdToComplete){
                    noOfGatesAfter = 1;
                    if(currentStatus != 'In Progress'){
                        ag.Status__c = 'In Progress';
                        noOfGatesAfter = 2;
                    }
                }
                if(currentStatus != 'Completed' && ag.Status__c == 'Completed'){
                    ag.Completed_Date__c = System.now();
                }
            }
            else if(noOfGatesAfter == 1){
                ag.Status__c = 'In Progress';
                noOfGatesAfter += 1;
            }
            else{
                ag.Status__c = 'Open';
            }
            if(ag.Status__c != 'Completed'){
                ag.Completed_Date__c = null;
            }
        }
        update assignedGates;
        return assignedGates;
    }
}