force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Rework</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replan</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/Task_Milestone__c.object-meta.xml
<CustomObject>
    <label>Task / Milestone</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Task / Milestone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks and Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Milestone__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Is_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Task_Milestone__c</referenceTo>
    <relationshipLabel>Sub Tasks and Milestones</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Tasks and Milestones</relationshipLabel>
    <relationshipName>Tasks_and_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <label>Progress</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks and Milestones</relationshipLabel>
    <relationshipName>Tasks_and_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Milestone__c/fields/Task_Milestone_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Milestone_Subject__c</fullName>
    <label>Task / Milestone Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GanttDataForTasks.cls
public with sharing class GanttDataForTasks {
    public GanttDataForTasks() {

    }

    @RemoteAction
    @AuraEnabled()
    public static Map<String, Object> getAllTasksAndMilestonesByProject(String currentRecordId) {
        List<GanttDataWrapper> ganttDataWrapperList = new List<GanttDataWrapper>();
        if(String.isNotBlank(currentRecordId)){
            Id recId = Id.valueOf(currentRecordId);
            String objName = recId.getSObjectType().getDescribe().getName();
            List<Task_Milestone__c> tasksAndMilestones = new List<Task_Milestone__c>();
            if(objName.equalsIgnoreCase('Project__c')){
                tasksAndMilestones = [SELECT Id, Name, Status__c, Progress__c, Task_Milestone_Subject__c, Start_Date__c, Due_Date__c, Parent__c, Is_Milestone__c, Project__c, Program__c 
                                        FROM Task_Milestone__c 
                                        WHERE Project__c =:  currentRecordId
                                        ORDER BY Start_Date__c];
            }
            else if(objName.equalsIgnoreCase('Program__c')){
                tasksAndMilestones = [SELECT Id, Name, Status__c, Progress__c, Task_Milestone_Subject__c, Start_Date__c, Due_Date__c, Parent__c, Is_Milestone__c, Project__c, Program__c 
                                        FROM Task_Milestone__c 
                                        WHERE Program__c =:  currentRecordId
                                        ORDER BY Start_Date__c];
            }

            for(Task_Milestone__c tm: tasksAndMilestones){
                ganttDataWrapperList.add(new GanttDataWrapper((tm.Is_Milestone__c? 'milestone':'task'), tm.Id, tm.Task_Milestone_Subject__c, Date.valueOf(tm.Start_Date__c), Date.valueOf(tm.Due_Date__c), tm.Parent__c, (tm.Progress__c != null? (tm.Progress__c/100) : 0) ));
            }
        }
        Map<String, Object> result = new Map<String, Object>{'tasks' => ganttDataWrapperList, 'links' => new List<String>() };
        return result;
    }
}