force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Forecast</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Fixed_Costs__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Costs__c</fullName>
    <label>Fixed Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Labour__c.field-meta.xml
<CustomField>
    <fullName>Labour__c</fullName>
    <label>Labour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Materials__c.field-meta.xml
<CustomField>
    <fullName>Materials__c</fullName>
    <label>Materials</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Resource_Cost__c + Material_Cost__c + Fixed_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Years.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
        <default>true</default>
        <label>2022</label>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <masterLabel>Years</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ForeCastController.cls
public with sharing class ForeCastController {

    @AuraEnabled
    public static List<ForeCast__c> fetchRecords(String versionId){
        try {
            System.debug('versionId--'+versionId);
            return [SELECT Id, Name, Year__c, Month__c, Labour__c, Materials__c, Fixed_Costs__c, Total__c, Project_Version__c from ForeCast__c where Project_Version__c=:versionId ORDER BY Name];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<ForeCast__c> saveRecords(List<ForeCast__c> foreCastList){
        try {
            if(!foreCastList.isEmpty()){
                update foreCastList;
            }
            return foreCastList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}