force-app/main/default/objects/Aggregator__c/Aggregator__c.object-meta.xml
<CustomObject>
    <label>Aggregator</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Aggregate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aggregator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aggregator__c/fields/Fixed_Expense__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Expense__c</fullName>
    <label>Fixed (Other) Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Aggregator__c/fields/Labour_Expense__c.field-meta.xml
<CustomField>
    <fullName>Labour_Expense__c</fullName>
    <label>Labour Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Aggregator__c/fields/Material_Expense__c.field-meta.xml
<CustomField>
    <fullName>Material_Expense__c</fullName>
    <label>Material Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Aggregator__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Aggregator</relationshipLabel>
    <relationshipName>Aggregator</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Aggregator__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Material_Expense__c + Labour_Expense__c + Fixed_Expense__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Aggregator__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT( YEAR ( TODAY() ))</defaultValue>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Forecast</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Fixed_Costs__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Costs__c</fullName>
    <label>Fixed Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Labour__c.field-meta.xml
<CustomField>
    <fullName>Labour__c</fullName>
    <label>Labour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Materials__c.field-meta.xml
<CustomField>
    <fullName>Materials__c</fullName>
    <label>Materials</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Project_Version__c.field-meta.xml
<CustomField>
    <fullName>Project_Version__c</fullName>
    <label>Project Version</label>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Resource_Cost__c + Material_Cost__c + Fixed_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active_Version__c.field-meta.xml
<CustomField>
    <fullName>Active_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project_Version__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Version__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Forecast__c</fullName>
    <formula>Active_Version__r.Total_Forecast__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Material_Cost__c</fullName>
    <formula>Active_Version__r.Total_Material_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Material Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Material_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Material_Forecast__c</fullName>
    <formula>Active_Version__r.Total_Material_Forecast__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Material Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Resource_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Resource_Cost__c</fullName>
    <formula>Active_Version__r.Total_Resource_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Resource Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/Project_Version__c.object-meta.xml
<CustomObject>
    <label>Project Version</label>
    <nameField>
        <label>Project Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Version__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <formula>Project__r.Active_Version__c =  Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Versions</relationshipLabel>
    <relationshipName>Project_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Total_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Forecast__c</fullName>
    <label>Total Forecast</label>
    <summarizedField>Forecast__c.Total__c</summarizedField>
    <summaryForeignKey>Forecast__c.Project_Version__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Total_Labour_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Labour_Forecast__c</fullName>
    <label>Total Labour Forecast</label>
    <summarizedField>Forecast__c.Labour__c</summarizedField>
    <summaryForeignKey>Forecast__c.Project_Version__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Total_Material_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Material_Cost__c</fullName>
    <label>Total Material Cost</label>
    <summarizedField>Aggregator__c.Material_Cost__c</summarizedField>
    <summaryForeignKey>Aggregator__c.Project_Version__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Total_Material_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Total_Material_Forecast__c</fullName>
    <label>Total Material Forecast</label>
    <summarizedField>Forecast__c.Material_Cost__c</summarizedField>
    <summaryForeignKey>Forecast__c.Project_Version__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Version__c/fields/Total_Resource_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Resource_Cost__c</fullName>
    <label>Total Resource Cost</label>
    <summarizedField>Resource_Engagement__c.Engagement_Cost__c</summarizedField>
    <summaryForeignKey>Resource_Engagement__c.Project_Version__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/Years.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
        <default>true</default>
        <label>2022</label>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <masterLabel>Years</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ForecastController.cls
public with sharing class ForecastController {

    @AuraEnabled
    public static Project_Version__c fetchRecords(String recordId){
        try {
            System.debug('recordId--'+recordId);
            String objectName = ((Id)recordId).getSObjectType().getDescribe().getName();
            String versionId = '';
            if(objectName=='Project__c'){
                for(Project__c p: [SELECT Id, Active_Version__c FROM Project__c WHERE Id=:recordId]){
                    versionId = p.Active_Version__c;
                }
            }
            else{
                versionId = recordId;
            }
            return String.isNotBlank(versionId)?[SELECT Id, Name, Project__c, Is_Primary__c, Total_Labour_Forecast__c, Total_Material_Forecast__c, Total_Forecast__c, Total_Material_Cost__c, Total_Resource_Cost__c, (Select Id, Name, Year__c, Month__c, Labour__c, Materials__c, Fixed_Costs__c, Total__c, Project_Version__c From Forecasts__r ORDER BY Name), (Select Id, Name, Year__c, Month__c, Material_Expense__c, Labour_Expense__c, Fixed_Expense__c, Total__c, Project_Version__c From Aggregator__r ORDER BY Name) FROM Project_Version__c WHERE Id=:versionId ]:new Project_Version__c();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Forecast__c> saveForecastRecords(List<Forecast__c> forecastList){
        try {
            if(!forecastList.isEmpty()){
                update forecastList;
            }
            return forecastList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Aggregator__c> saveAggregatorRecords(List<Aggregator__c> aggregatorList){
        try {
            if(!aggregatorList.isEmpty()){
                update aggregatorList;
            }
            return aggregatorList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ProjectVersionWrapper{
        @AuraEnabled
        public List<FinancialWrapper> forecasts         {get; set;}
        @AuraEnabled
        public List<FinancialWrapper> aggregators       {get; set;}
        @AuraEnabled
        public Project_Version__c projectVersion        {get; set;}
    }

    public class FinancialWrapper{
        @AuraEnabled
        public id recordId                              {get; set;}
        @AuraEnabled
        public integer month                            {get; set;}
        @AuraEnabled
        public integer year                             {get; set;}
        @AuraEnabled
        public Decimal labourAmount                     {get; set;}
        @AuraEnabled
        public Decimal materialAmount                   {get; set;}
        @AuraEnabled
        public Decimal fixedAmount                      {get; set;}
        @AuraEnabled
        public Decimal total{
            get{
                return this.labourAmount + this.materialAmount + this.fixedAmount;
            } set;
        }
        @AuraEnabled
        public boolean disableEdit                      {get; set;}
        @AuraEnabled
        public String headerValue                       {get; set;}

        public FinancialWrapper(Id recId, Interger m, Integer y, Decimal lA, Decimal mA, Decimal fA){
            this.recordId = recId;
            this.month = m;
            this.year = y;
            this.labourAmount = lA;
            this.materialAmount = mA;
            this.fixedAmount = fA;
            
        }
    }
}